name: scrobblium
description: "A app to track music in the background"
publish_to: 'none'
version: 0.1.0-0-Beta

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  path_provider: ^2.1.2
  flex_color_scheme: ^7.3.1
  provider: ^6.1.2
  dynamic_color: ^1.7.0
  google_nav_bar: ^5.0.6
  easy_debounce: ^2.0.3
  fluttertoast: ^8.2.6
  protobuf: ^3.1.0
  url_launcher: ^6.3.0
  package_info_plus: ^8.0.0

  flutter_settings_screens:
    path: externel/flutter_settings_screens-0.3.4
  anim_search_bar:
    path: externel/anim_search_bar-2.0.3
  installed_apps:
    path: externel/installed_apps
  logging: ^1.2.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true