// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/song_datam.proto
// Protobuf Java Version: 4.27.1

package io.github.chikyukido.scrobblium.messages;

public interface SongDataListMOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.github.chikyukido.scrobblium.messages.SongDataListM)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.github.chikyukido.scrobblium.messages.SongDataM songs = 1;</code>
   */
  java.util.List<io.github.chikyukido.scrobblium.messages.SongDataM> 
      getSongsList();
  /**
   * <code>repeated .io.github.chikyukido.scrobblium.messages.SongDataM songs = 1;</code>
   */
  io.github.chikyukido.scrobblium.messages.SongDataM getSongs(int index);
  /**
   * <code>repeated .io.github.chikyukido.scrobblium.messages.SongDataM songs = 1;</code>
   */
  int getSongsCount();
  /**
   * <code>repeated .io.github.chikyukido.scrobblium.messages.SongDataM songs = 1;</code>
   */
  java.util.List<? extends io.github.chikyukido.scrobblium.messages.SongDataMOrBuilder> 
      getSongsOrBuilderList();
  /**
   * <code>repeated .io.github.chikyukido.scrobblium.messages.SongDataM songs = 1;</code>
   */
  io.github.chikyukido.scrobblium.messages.SongDataMOrBuilder getSongsOrBuilder(
      int index);
}
