// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/song_datam.proto
// Protobuf Java Version: 4.33.1

package io.github.chikyukido.scrobblium.messages;

/**
 * Protobuf type {@code io.github.chikyukido.scrobblium.messages.SongDataM}
 */
@com.google.protobuf.Generated
public final class SongDataM extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:io.github.chikyukido.scrobblium.messages.SongDataM)
    SongDataMOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "SongDataM");
  }
  // Use SongDataM.newBuilder() to construct.
  private SongDataM(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SongDataM() {
    artist_ = "";
    title_ = "";
    album_ = "";
    albumAuthor_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.chikyukido.scrobblium.messages.SongDatam.internal_static_io_github_chikyukido_scrobblium_messages_SongDataM_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.chikyukido.scrobblium.messages.SongDatam.internal_static_io_github_chikyukido_scrobblium_messages_SongDataM_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.chikyukido.scrobblium.messages.SongDataM.class, io.github.chikyukido.scrobblium.messages.SongDataM.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;
  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int ARTIST_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object artist_ = "";
  /**
   * <code>string artist = 2;</code>
   * @return The artist.
   */
  @java.lang.Override
  public java.lang.String getArtist() {
    java.lang.Object ref = artist_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      artist_ = s;
      return s;
    }
  }
  /**
   * <code>string artist = 2;</code>
   * @return The bytes for artist.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getArtistBytes() {
    java.lang.Object ref = artist_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      artist_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TITLE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <code>string title = 3;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 3;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALBUM_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object album_ = "";
  /**
   * <code>string album = 4;</code>
   * @return The album.
   */
  @java.lang.Override
  public java.lang.String getAlbum() {
    java.lang.Object ref = album_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      album_ = s;
      return s;
    }
  }
  /**
   * <code>string album = 4;</code>
   * @return The bytes for album.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAlbumBytes() {
    java.lang.Object ref = album_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      album_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALBUMAUTHOR_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object albumAuthor_ = "";
  /**
   * <code>string albumAuthor = 5;</code>
   * @return The albumAuthor.
   */
  @java.lang.Override
  public java.lang.String getAlbumAuthor() {
    java.lang.Object ref = albumAuthor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      albumAuthor_ = s;
      return s;
    }
  }
  /**
   * <code>string albumAuthor = 5;</code>
   * @return The bytes for albumAuthor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAlbumAuthorBytes() {
    java.lang.Object ref = albumAuthor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      albumAuthor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAXPROGRESS_FIELD_NUMBER = 6;
  private int maxProgress_ = 0;
  /**
   * <code>int32 maxProgress = 6;</code>
   * @return The maxProgress.
   */
  @java.lang.Override
  public int getMaxProgress() {
    return maxProgress_;
  }

  public static final int STARTTIME_FIELD_NUMBER = 7;
  private long startTime_ = 0L;
  /**
   * <code>int64 startTime = 7;</code>
   * @return The startTime.
   */
  @java.lang.Override
  public long getStartTime() {
    return startTime_;
  }

  public static final int PROGRESS_FIELD_NUMBER = 8;
  private int progress_ = 0;
  /**
   * <code>int32 progress = 8;</code>
   * @return The progress.
   */
  @java.lang.Override
  public int getProgress() {
    return progress_;
  }

  public static final int ENDTIME_FIELD_NUMBER = 9;
  private long endTime_ = 0L;
  /**
   * <code>int64 endTime = 9;</code>
   * @return The endTime.
   */
  @java.lang.Override
  public long getEndTime() {
    return endTime_;
  }

  public static final int TIMELISTENED_FIELD_NUMBER = 10;
  private int timeListened_ = 0;
  /**
   * <code>int32 timeListened = 10;</code>
   * @return The timeListened.
   */
  @java.lang.Override
  public int getTimeListened() {
    return timeListened_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(artist_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, artist_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, title_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(album_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, album_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(albumAuthor_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, albumAuthor_);
    }
    if (maxProgress_ != 0) {
      output.writeInt32(6, maxProgress_);
    }
    if (startTime_ != 0L) {
      output.writeInt64(7, startTime_);
    }
    if (progress_ != 0) {
      output.writeInt32(8, progress_);
    }
    if (endTime_ != 0L) {
      output.writeInt64(9, endTime_);
    }
    if (timeListened_ != 0) {
      output.writeInt32(10, timeListened_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(artist_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, artist_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, title_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(album_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, album_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(albumAuthor_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, albumAuthor_);
    }
    if (maxProgress_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, maxProgress_);
    }
    if (startTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, startTime_);
    }
    if (progress_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, progress_);
    }
    if (endTime_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, endTime_);
    }
    if (timeListened_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, timeListened_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.chikyukido.scrobblium.messages.SongDataM)) {
      return super.equals(obj);
    }
    io.github.chikyukido.scrobblium.messages.SongDataM other = (io.github.chikyukido.scrobblium.messages.SongDataM) obj;

    if (getId()
        != other.getId()) return false;
    if (!getArtist()
        .equals(other.getArtist())) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getAlbum()
        .equals(other.getAlbum())) return false;
    if (!getAlbumAuthor()
        .equals(other.getAlbumAuthor())) return false;
    if (getMaxProgress()
        != other.getMaxProgress()) return false;
    if (getStartTime()
        != other.getStartTime()) return false;
    if (getProgress()
        != other.getProgress()) return false;
    if (getEndTime()
        != other.getEndTime()) return false;
    if (getTimeListened()
        != other.getTimeListened()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + ARTIST_FIELD_NUMBER;
    hash = (53 * hash) + getArtist().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + ALBUM_FIELD_NUMBER;
    hash = (53 * hash) + getAlbum().hashCode();
    hash = (37 * hash) + ALBUMAUTHOR_FIELD_NUMBER;
    hash = (53 * hash) + getAlbumAuthor().hashCode();
    hash = (37 * hash) + MAXPROGRESS_FIELD_NUMBER;
    hash = (53 * hash) + getMaxProgress();
    hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getStartTime());
    hash = (37 * hash) + PROGRESS_FIELD_NUMBER;
    hash = (53 * hash) + getProgress();
    hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getEndTime());
    hash = (37 * hash) + TIMELISTENED_FIELD_NUMBER;
    hash = (53 * hash) + getTimeListened();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.chikyukido.scrobblium.messages.SongDataM parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chikyukido.scrobblium.messages.SongDataM parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chikyukido.scrobblium.messages.SongDataM parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chikyukido.scrobblium.messages.SongDataM parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chikyukido.scrobblium.messages.SongDataM parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chikyukido.scrobblium.messages.SongDataM parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chikyukido.scrobblium.messages.SongDataM parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.chikyukido.scrobblium.messages.SongDataM parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.chikyukido.scrobblium.messages.SongDataM parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.chikyukido.scrobblium.messages.SongDataM parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.chikyukido.scrobblium.messages.SongDataM parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.chikyukido.scrobblium.messages.SongDataM parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.chikyukido.scrobblium.messages.SongDataM prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.github.chikyukido.scrobblium.messages.SongDataM}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.github.chikyukido.scrobblium.messages.SongDataM)
      io.github.chikyukido.scrobblium.messages.SongDataMOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.chikyukido.scrobblium.messages.SongDatam.internal_static_io_github_chikyukido_scrobblium_messages_SongDataM_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.chikyukido.scrobblium.messages.SongDatam.internal_static_io_github_chikyukido_scrobblium_messages_SongDataM_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.chikyukido.scrobblium.messages.SongDataM.class, io.github.chikyukido.scrobblium.messages.SongDataM.Builder.class);
    }

    // Construct using io.github.chikyukido.scrobblium.messages.SongDataM.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      artist_ = "";
      title_ = "";
      album_ = "";
      albumAuthor_ = "";
      maxProgress_ = 0;
      startTime_ = 0L;
      progress_ = 0;
      endTime_ = 0L;
      timeListened_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.chikyukido.scrobblium.messages.SongDatam.internal_static_io_github_chikyukido_scrobblium_messages_SongDataM_descriptor;
    }

    @java.lang.Override
    public io.github.chikyukido.scrobblium.messages.SongDataM getDefaultInstanceForType() {
      return io.github.chikyukido.scrobblium.messages.SongDataM.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.chikyukido.scrobblium.messages.SongDataM build() {
      io.github.chikyukido.scrobblium.messages.SongDataM result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.chikyukido.scrobblium.messages.SongDataM buildPartial() {
      io.github.chikyukido.scrobblium.messages.SongDataM result = new io.github.chikyukido.scrobblium.messages.SongDataM(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.chikyukido.scrobblium.messages.SongDataM result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.artist_ = artist_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.album_ = album_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.albumAuthor_ = albumAuthor_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.maxProgress_ = maxProgress_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.startTime_ = startTime_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.progress_ = progress_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.endTime_ = endTime_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.timeListened_ = timeListened_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.chikyukido.scrobblium.messages.SongDataM) {
        return mergeFrom((io.github.chikyukido.scrobblium.messages.SongDataM)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.chikyukido.scrobblium.messages.SongDataM other) {
      if (other == io.github.chikyukido.scrobblium.messages.SongDataM.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getArtist().isEmpty()) {
        artist_ = other.artist_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getAlbum().isEmpty()) {
        album_ = other.album_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getAlbumAuthor().isEmpty()) {
        albumAuthor_ = other.albumAuthor_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getMaxProgress() != 0) {
        setMaxProgress(other.getMaxProgress());
      }
      if (other.getStartTime() != 0L) {
        setStartTime(other.getStartTime());
      }
      if (other.getProgress() != 0) {
        setProgress(other.getProgress());
      }
      if (other.getEndTime() != 0L) {
        setEndTime(other.getEndTime());
      }
      if (other.getTimeListened() != 0) {
        setTimeListened(other.getTimeListened());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              artist_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              album_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              albumAuthor_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              maxProgress_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              startTime_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              progress_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              endTime_ = input.readInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              timeListened_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object artist_ = "";
    /**
     * <code>string artist = 2;</code>
     * @return The artist.
     */
    public java.lang.String getArtist() {
      java.lang.Object ref = artist_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        artist_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string artist = 2;</code>
     * @return The bytes for artist.
     */
    public com.google.protobuf.ByteString
        getArtistBytes() {
      java.lang.Object ref = artist_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        artist_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string artist = 2;</code>
     * @param value The artist to set.
     * @return This builder for chaining.
     */
    public Builder setArtist(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      artist_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string artist = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearArtist() {
      artist_ = getDefaultInstance().getArtist();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string artist = 2;</code>
     * @param value The bytes for artist to set.
     * @return This builder for chaining.
     */
    public Builder setArtistBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      artist_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 3;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 3;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 3;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object album_ = "";
    /**
     * <code>string album = 4;</code>
     * @return The album.
     */
    public java.lang.String getAlbum() {
      java.lang.Object ref = album_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        album_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string album = 4;</code>
     * @return The bytes for album.
     */
    public com.google.protobuf.ByteString
        getAlbumBytes() {
      java.lang.Object ref = album_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        album_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string album = 4;</code>
     * @param value The album to set.
     * @return This builder for chaining.
     */
    public Builder setAlbum(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      album_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string album = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlbum() {
      album_ = getDefaultInstance().getAlbum();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string album = 4;</code>
     * @param value The bytes for album to set.
     * @return This builder for chaining.
     */
    public Builder setAlbumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      album_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object albumAuthor_ = "";
    /**
     * <code>string albumAuthor = 5;</code>
     * @return The albumAuthor.
     */
    public java.lang.String getAlbumAuthor() {
      java.lang.Object ref = albumAuthor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        albumAuthor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string albumAuthor = 5;</code>
     * @return The bytes for albumAuthor.
     */
    public com.google.protobuf.ByteString
        getAlbumAuthorBytes() {
      java.lang.Object ref = albumAuthor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        albumAuthor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string albumAuthor = 5;</code>
     * @param value The albumAuthor to set.
     * @return This builder for chaining.
     */
    public Builder setAlbumAuthor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      albumAuthor_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string albumAuthor = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlbumAuthor() {
      albumAuthor_ = getDefaultInstance().getAlbumAuthor();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string albumAuthor = 5;</code>
     * @param value The bytes for albumAuthor to set.
     * @return This builder for chaining.
     */
    public Builder setAlbumAuthorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      albumAuthor_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private int maxProgress_ ;
    /**
     * <code>int32 maxProgress = 6;</code>
     * @return The maxProgress.
     */
    @java.lang.Override
    public int getMaxProgress() {
      return maxProgress_;
    }
    /**
     * <code>int32 maxProgress = 6;</code>
     * @param value The maxProgress to set.
     * @return This builder for chaining.
     */
    public Builder setMaxProgress(int value) {

      maxProgress_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 maxProgress = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxProgress() {
      bitField0_ = (bitField0_ & ~0x00000020);
      maxProgress_ = 0;
      onChanged();
      return this;
    }

    private long startTime_ ;
    /**
     * <code>int64 startTime = 7;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public long getStartTime() {
      return startTime_;
    }
    /**
     * <code>int64 startTime = 7;</code>
     * @param value The startTime to set.
     * @return This builder for chaining.
     */
    public Builder setStartTime(long value) {

      startTime_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 startTime = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartTime() {
      bitField0_ = (bitField0_ & ~0x00000040);
      startTime_ = 0L;
      onChanged();
      return this;
    }

    private int progress_ ;
    /**
     * <code>int32 progress = 8;</code>
     * @return The progress.
     */
    @java.lang.Override
    public int getProgress() {
      return progress_;
    }
    /**
     * <code>int32 progress = 8;</code>
     * @param value The progress to set.
     * @return This builder for chaining.
     */
    public Builder setProgress(int value) {

      progress_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int32 progress = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearProgress() {
      bitField0_ = (bitField0_ & ~0x00000080);
      progress_ = 0;
      onChanged();
      return this;
    }

    private long endTime_ ;
    /**
     * <code>int64 endTime = 9;</code>
     * @return The endTime.
     */
    @java.lang.Override
    public long getEndTime() {
      return endTime_;
    }
    /**
     * <code>int64 endTime = 9;</code>
     * @param value The endTime to set.
     * @return This builder for chaining.
     */
    public Builder setEndTime(long value) {

      endTime_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int64 endTime = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndTime() {
      bitField0_ = (bitField0_ & ~0x00000100);
      endTime_ = 0L;
      onChanged();
      return this;
    }

    private int timeListened_ ;
    /**
     * <code>int32 timeListened = 10;</code>
     * @return The timeListened.
     */
    @java.lang.Override
    public int getTimeListened() {
      return timeListened_;
    }
    /**
     * <code>int32 timeListened = 10;</code>
     * @param value The timeListened to set.
     * @return This builder for chaining.
     */
    public Builder setTimeListened(int value) {

      timeListened_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>int32 timeListened = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeListened() {
      bitField0_ = (bitField0_ & ~0x00000200);
      timeListened_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.github.chikyukido.scrobblium.messages.SongDataM)
  }

  // @@protoc_insertion_point(class_scope:io.github.chikyukido.scrobblium.messages.SongDataM)
  private static final io.github.chikyukido.scrobblium.messages.SongDataM DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.chikyukido.scrobblium.messages.SongDataM();
  }

  public static io.github.chikyukido.scrobblium.messages.SongDataM getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SongDataM>
      PARSER = new com.google.protobuf.AbstractParser<SongDataM>() {
    @java.lang.Override
    public SongDataM parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SongDataM> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SongDataM> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.chikyukido.scrobblium.messages.SongDataM getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

