// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/song_datam.proto
// Protobuf Java Version: 4.33.1

package io.github.chikyukido.scrobblium.messages;

@com.google.protobuf.Generated
public final class SongDatam extends com.google.protobuf.GeneratedFile {
  private SongDatam() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 33,
      /* patch= */ 1,
      /* suffix= */ "",
      "SongDatam");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_chikyukido_scrobblium_messages_SongDataM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_github_chikyukido_scrobblium_messages_SongDataM_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_github_chikyukido_scrobblium_messages_SongDataListM_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_io_github_chikyukido_scrobblium_messages_SongDataListM_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026proto/song_datam.proto\022(io.github.chik" +
      "yukido.scrobblium.messages\"\273\001\n\tSongDataM" +
      "\022\n\n\002id\030\001 \001(\005\022\016\n\006artist\030\002 \001(\t\022\r\n\005title\030\003 " +
      "\001(\t\022\r\n\005album\030\004 \001(\t\022\023\n\013albumAuthor\030\005 \001(\t\022" +
      "\023\n\013maxProgress\030\006 \001(\005\022\021\n\tstartTime\030\007 \001(\003\022" +
      "\020\n\010progress\030\010 \001(\005\022\017\n\007endTime\030\t \001(\003\022\024\n\014ti" +
      "meListened\030\n \001(\005\"S\n\rSongDataListM\022B\n\005son" +
      "gs\030\001 \003(\01323.io.github.chikyukido.scrobbli" +
      "um.messages.SongDataMB\004H\001P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_github_chikyukido_scrobblium_messages_SongDataM_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_io_github_chikyukido_scrobblium_messages_SongDataM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_github_chikyukido_scrobblium_messages_SongDataM_descriptor,
        new java.lang.String[] { "Id", "Artist", "Title", "Album", "AlbumAuthor", "MaxProgress", "StartTime", "Progress", "EndTime", "TimeListened", });
    internal_static_io_github_chikyukido_scrobblium_messages_SongDataListM_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_io_github_chikyukido_scrobblium_messages_SongDataListM_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_io_github_chikyukido_scrobblium_messages_SongDataListM_descriptor,
        new java.lang.String[] { "Songs", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
