// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: proto/song_datam.proto
// Protobuf Java Version: 4.27.1

package io.github.chikyukido.scrobblium.messages;

/**
 * Protobuf type {@code io.github.chikyukido.scrobblium.messages.SongDataM}
 */
public final class SongDataM extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:io.github.chikyukido.scrobblium.messages.SongDataM)
    SongDataMOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 1,
      /* suffix= */ "",
      SongDataM.class.getName());
  }
  // Use SongDataM.newBuilder() to construct.
  private SongDataM(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SongDataM() {
    artist_ = "";
    title_ = "";
    album_ = "";
    albumAuthor_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.chikyukido.scrobblium.messages.SongDatam.internal_static_io_github_chikyukido_scrobblium_messages_SongDataM_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.chikyukido.scrobblium.messages.SongDatam.internal_static_io_github_chikyukido_scrobblium_messages_SongDataM_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.chikyukido.scrobblium.messages.SongDataM.class, io.github.chikyukido.scrobblium.messages.SongDataM.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_ = 0L;
  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public long getId() {
    return id_;
  }

  public static final int ARTIST_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object artist_ = "";
  /**
   * <code>string artist = 2;</code>
   * @return The artist.
   */
  @java.lang.Override
  public java.lang.String getArtist() {
    java.lang.Object ref = artist_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      artist_ = s;
      return s;
    }
  }
  /**
   * <code>string artist = 2;</code>
   * @return The bytes for artist.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getArtistBytes() {
    java.lang.Object ref = artist_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      artist_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TITLE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <code>string title = 3;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 3;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALBUM_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object album_ = "";
  /**
   * <code>string album = 4;</code>
   * @return The album.
   */
  @java.lang.Override
  public java.lang.String getAlbum() {
    java.lang.Object ref = album_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      album_ = s;
      return s;
    }
  }
  /**
   * <code>string album = 4;</code>
   * @return The bytes for album.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAlbumBytes() {
    java.lang.Object ref = album_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      album_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ALBUMAUTHOR_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object albumAuthor_ = "";
  /**
   * <code>string albumAuthor = 5;</code>
   * @return The albumAuthor.
   */
  @java.lang.Override
  public java.lang.String getAlbumAuthor() {
    java.lang.Object ref = albumAuthor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      albumAuthor_ = s;
      return s;
    }
  }
  /**
   * <code>string albumAuthor = 5;</code>
   * @return The bytes for albumAuthor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAlbumAuthorBytes() {
    java.lang.Object ref = albumAuthor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      albumAuthor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAXPROGRESS_FIELD_NUMBER = 6;
  private long maxProgress_ = 0L;
  /**
   * <code>int64 maxProgress = 6;</code>
   * @return The maxProgress.
   */
  @java.lang.Override
  public long getMaxProgress() {
    return maxProgress_;
  }

  public static final int STARTTIME_FIELD_NUMBER = 7;
  private long startTime_ = 0L;
  /**
   * <code>int64 startTime = 7;</code>
   * @return The startTime.
   */
  @java.lang.Override
  public long getStartTime() {
    return startTime_;
  }

  public static final int PROGRESS_FIELD_NUMBER = 8;
  private long progress_ = 0L;
  /**
   * <code>int64 progress = 8;</code>
   * @return The progress.
   */
  @java.lang.Override
  public long getProgress() {
    return progress_;
  }

  public static final int ENDTIME_FIELD_NUMBER = 9;
  private long endTime_ = 0L;
  /**
   * <code>int64 endTime = 9;</code>
   * @return The endTime.
   */
  @java.lang.Override
  public long getEndTime() {
    return endTime_;
  }

  public static final int TIMELISTENED_FIELD_NUMBER = 10;
  private int timeListened_ = 0;
  /**
   * <code>int32 timeListened = 10;</code>
   * @return The timeListened.
   */
  @java.lang.Override
  public int getTimeListened() {
    return timeListened_;
  }

  public static io.github.chikyukido.scrobblium.messages.SongDataM parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chikyukido.scrobblium.messages.SongDataM parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chikyukido.scrobblium.messages.SongDataM parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chikyukido.scrobblium.messages.SongDataM parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chikyukido.scrobblium.messages.SongDataM parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chikyukido.scrobblium.messages.SongDataM parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chikyukido.scrobblium.messages.SongDataM parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.chikyukido.scrobblium.messages.SongDataM parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.chikyukido.scrobblium.messages.SongDataM parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.chikyukido.scrobblium.messages.SongDataM parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.chikyukido.scrobblium.messages.SongDataM parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.chikyukido.scrobblium.messages.SongDataM parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.chikyukido.scrobblium.messages.SongDataM prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.github.chikyukido.scrobblium.messages.SongDataM}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.github.chikyukido.scrobblium.messages.SongDataM)
      io.github.chikyukido.scrobblium.messages.SongDataMOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.chikyukido.scrobblium.messages.SongDatam.internal_static_io_github_chikyukido_scrobblium_messages_SongDataM_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.chikyukido.scrobblium.messages.SongDatam.internal_static_io_github_chikyukido_scrobblium_messages_SongDataM_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.chikyukido.scrobblium.messages.SongDataM.class, io.github.chikyukido.scrobblium.messages.SongDataM.Builder.class);
    }

    // Construct using io.github.chikyukido.scrobblium.messages.SongDataM.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0L;
      artist_ = "";
      title_ = "";
      album_ = "";
      albumAuthor_ = "";
      maxProgress_ = 0L;
      startTime_ = 0L;
      progress_ = 0L;
      endTime_ = 0L;
      timeListened_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.chikyukido.scrobblium.messages.SongDatam.internal_static_io_github_chikyukido_scrobblium_messages_SongDataM_descriptor;
    }

    @java.lang.Override
    public io.github.chikyukido.scrobblium.messages.SongDataM getDefaultInstanceForType() {
      return io.github.chikyukido.scrobblium.messages.SongDataM.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.chikyukido.scrobblium.messages.SongDataM build() {
      io.github.chikyukido.scrobblium.messages.SongDataM result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.chikyukido.scrobblium.messages.SongDataM buildPartial() {
      io.github.chikyukido.scrobblium.messages.SongDataM result = new io.github.chikyukido.scrobblium.messages.SongDataM(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.chikyukido.scrobblium.messages.SongDataM result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.artist_ = artist_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.album_ = album_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.albumAuthor_ = albumAuthor_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.maxProgress_ = maxProgress_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.startTime_ = startTime_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.progress_ = progress_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.endTime_ = endTime_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.timeListened_ = timeListened_;
      }
    }

    private int bitField0_;

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(long value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object artist_ = "";
    /**
     * <code>string artist = 2;</code>
     * @return The artist.
     */
    public java.lang.String getArtist() {
      java.lang.Object ref = artist_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        artist_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string artist = 2;</code>
     * @return The bytes for artist.
     */
    public com.google.protobuf.ByteString
        getArtistBytes() {
      java.lang.Object ref = artist_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        artist_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string artist = 2;</code>
     * @param value The artist to set.
     * @return This builder for chaining.
     */
    public Builder setArtist(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      artist_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string artist = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearArtist() {
      artist_ = getDefaultInstance().getArtist();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string artist = 2;</code>
     * @param value The bytes for artist to set.
     * @return This builder for chaining.
     */
    public Builder setArtistBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      artist_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 3;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 3;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 3;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string title = 3;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object album_ = "";
    /**
     * <code>string album = 4;</code>
     * @return The album.
     */
    public java.lang.String getAlbum() {
      java.lang.Object ref = album_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        album_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string album = 4;</code>
     * @return The bytes for album.
     */
    public com.google.protobuf.ByteString
        getAlbumBytes() {
      java.lang.Object ref = album_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        album_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string album = 4;</code>
     * @param value The album to set.
     * @return This builder for chaining.
     */
    public Builder setAlbum(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      album_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string album = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlbum() {
      album_ = getDefaultInstance().getAlbum();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string album = 4;</code>
     * @param value The bytes for album to set.
     * @return This builder for chaining.
     */
    public Builder setAlbumBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      album_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object albumAuthor_ = "";
    /**
     * <code>string albumAuthor = 5;</code>
     * @return The albumAuthor.
     */
    public java.lang.String getAlbumAuthor() {
      java.lang.Object ref = albumAuthor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        albumAuthor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string albumAuthor = 5;</code>
     * @return The bytes for albumAuthor.
     */
    public com.google.protobuf.ByteString
        getAlbumAuthorBytes() {
      java.lang.Object ref = albumAuthor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        albumAuthor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string albumAuthor = 5;</code>
     * @param value The albumAuthor to set.
     * @return This builder for chaining.
     */
    public Builder setAlbumAuthor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      albumAuthor_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string albumAuthor = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearAlbumAuthor() {
      albumAuthor_ = getDefaultInstance().getAlbumAuthor();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string albumAuthor = 5;</code>
     * @param value The bytes for albumAuthor to set.
     * @return This builder for chaining.
     */
    public Builder setAlbumAuthorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      albumAuthor_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private long maxProgress_ ;
    /**
     * <code>int64 maxProgress = 6;</code>
     * @return The maxProgress.
     */
    @java.lang.Override
    public long getMaxProgress() {
      return maxProgress_;
    }
    /**
     * <code>int64 maxProgress = 6;</code>
     * @param value The maxProgress to set.
     * @return This builder for chaining.
     */
    public Builder setMaxProgress(long value) {

      maxProgress_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 maxProgress = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxProgress() {
      bitField0_ = (bitField0_ & ~0x00000020);
      maxProgress_ = 0L;
      onChanged();
      return this;
    }

    private long startTime_ ;
    /**
     * <code>int64 startTime = 7;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public long getStartTime() {
      return startTime_;
    }
    /**
     * <code>int64 startTime = 7;</code>
     * @param value The startTime to set.
     * @return This builder for chaining.
     */
    public Builder setStartTime(long value) {

      startTime_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 startTime = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartTime() {
      bitField0_ = (bitField0_ & ~0x00000040);
      startTime_ = 0L;
      onChanged();
      return this;
    }

    private long progress_ ;
    /**
     * <code>int64 progress = 8;</code>
     * @return The progress.
     */
    @java.lang.Override
    public long getProgress() {
      return progress_;
    }
    /**
     * <code>int64 progress = 8;</code>
     * @param value The progress to set.
     * @return This builder for chaining.
     */
    public Builder setProgress(long value) {

      progress_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int64 progress = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearProgress() {
      bitField0_ = (bitField0_ & ~0x00000080);
      progress_ = 0L;
      onChanged();
      return this;
    }

    private long endTime_ ;
    /**
     * <code>int64 endTime = 9;</code>
     * @return The endTime.
     */
    @java.lang.Override
    public long getEndTime() {
      return endTime_;
    }
    /**
     * <code>int64 endTime = 9;</code>
     * @param value The endTime to set.
     * @return This builder for chaining.
     */
    public Builder setEndTime(long value) {

      endTime_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int64 endTime = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndTime() {
      bitField0_ = (bitField0_ & ~0x00000100);
      endTime_ = 0L;
      onChanged();
      return this;
    }

    private int timeListened_ ;
    /**
     * <code>int32 timeListened = 10;</code>
     * @return The timeListened.
     */
    @java.lang.Override
    public int getTimeListened() {
      return timeListened_;
    }
    /**
     * <code>int32 timeListened = 10;</code>
     * @param value The timeListened to set.
     * @return This builder for chaining.
     */
    public Builder setTimeListened(int value) {

      timeListened_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>int32 timeListened = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeListened() {
      bitField0_ = (bitField0_ & ~0x00000200);
      timeListened_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.github.chikyukido.scrobblium.messages.SongDataM)
  }

  // @@protoc_insertion_point(class_scope:io.github.chikyukido.scrobblium.messages.SongDataM)
  private static final io.github.chikyukido.scrobblium.messages.SongDataM DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.chikyukido.scrobblium.messages.SongDataM();
  }

  public static io.github.chikyukido.scrobblium.messages.SongDataM getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SongDataM>
      PARSER = new com.google.protobuf.AbstractParser<SongDataM>() {
    @java.lang.Override
    public SongDataM parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SongDataM> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SongDataM> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.chikyukido.scrobblium.messages.SongDataM getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

